apiVersion: v2
name: statistics-for-strava
version: 0.5.5
description: A Helm chart for Statistics for Strava, a self-hosted web application that provides insights and analytics for Strava activities.
type: application

icon: https://github.com/robiningelbrecht/statistics-for-strava/blob/master/public/assets/images/logo.svg
home: https://github.com/christian-vdz/helm-charts/charts/statistics-for-strava
sources: 
  - https://github.com/hhftechnology/statistics-for-strava
appVersion: "v4.7.9"

maintainers:
  - name: christian-vdz
    email: christian@slashops.fr
    url: https://github.com/christian-vdz
