nameOverride: ""
fullnameOverride: ""

replicaCount: 1
httpHost: localhost
timezone: Europe/Paris

strava:
  # Strava API credentials. Required if useExistingSecret is false.
  clientId: ""
  clientSecret: ""
  refreshToken: ""
  # Set to true to use an existing secret instead of creating a new one with the provided Strava credentials.
  useExistingSecret: false
  existingSecretName: ""

# Override default config values. See config/default.yaml for all available options.
# Athlete's birth and weight history dates are required for the app to import data from Strava.
config:
  general:
    athlete:
      birthday: '2000-01-01'
      weightHistory:
        "2000-01-01": 60

# Set gear maintenance config values. See config/example-gear-maintenance.yaml for all available options.
# Note: the gear maintenance feature is disabled by default. Set `gearMaintenanceConfig.enabled` to true to enable it.
gearMaintenanceConfig:
  enabled: false

app:
  image:
    pullPolicy: IfNotPresent
    repository: robiningelbrecht/strava-statistics
    tag: "" # Defaults to chart appVersion
  port: 8080
  readinessProbe:
    httpGet:
      path: /
      port: http
  livenessProbe:
    exec:
      command:
        - curl
        - -f
        - http://localhost:2019/metrics
    initialDelaySeconds: 60
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    # limits:
    #   cpu: 1000m
    #   memory: 2048Mi

service:
  type: ClusterIP
  port: 8080

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /headers
  extraHostnames: []
    # - statistics-for-strava.local

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []
  extraHosts: []
    # - host: statistics-for-strava.local
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific

podLabels: {}
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

affinity: {}
nodeSelector: {}
tolerations: []

imagePullSecrets: []
