apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: init-folders
          image: busybox
          command: ['sh', '-c', 'mkdir -p /app/app-data/{db,documents}']
          volumeMounts:
            - name: {{ include "app.fullname" . }}-claim0
              mountPath: /app/app-data
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}-rootless"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ include "app.fullname" . }}-claim0
              mountPath: /app/app-data
          env:
            - name: APP_BASE_URL
              value: "http://{{ .Values.baseUrl }}:{{ .Values.app.port }}"
            - name: PORT
              value: "{{ .Values.app.port }}"
          {{- with .Values.papra.extraEnv }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
            {{- if not .Values.papra.useExistingSecret }}
                name: {{ include "app.fullname" . }}
            {{- else }}
                name: {{ .Values.papra.existingSecretName }}
            {{- end }}
            {{- with .Values.papra.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ include "app.fullname" . }}-claim0
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-claim0
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
