apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- $default := .Files.Get "config/default.yaml" | fromYaml }}
{{- $override := .Values.config | default dict }}
{{- $merged := mergeOverwrite $default $override }}
data:
  config.yaml: |
{{ $merged | toYaml | indent 4 }}
{{- if .Values.gearMaintenanceConfig.enabled }}
{{- with .Values.gearMaintenanceConfig }}
  gear-maintenance.yaml: |
{{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
