{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  APP_SECRET: {{ .Values.appSecret | b64enc | quote }}
  ADMIN_USERNAME: {{ .Values.admin.username | b64enc | quote }}
  ADMIN_PASSWORD_HASH: {{ .Values.admin.passwordHash | b64enc | quote }}
{{- end }}
