{{- if and (not .Values.strava.useExistingSecret) (eq .Values.importMode "stravaApi") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-strava
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  STRAVA_CLIENT_ID: {{ .Values.strava.clientId | b64enc | quote }}
  STRAVA_CLIENT_SECRET: {{ .Values.strava.clientSecret | b64enc | quote }}
  STRAVA_REFRESH_TOKEN: {{ .Values.strava.refreshToken | b64enc | quote }}
{{- end }}
